### ISSUE TITLE
gem debugger not supported by ruby version

### ISSUE THREAD

**Issue by pacuna** [luctus/rails-vagrant-starter#2]
I'm having this error when running bundle:

```
ERROR:  Error installing debugger:
    ERROR: Failed to build gem native extension.

```

In the debugger [repo](https://github.com/cldwalker/debugger) the author says that ruby >= 2.0 is not supported.

**Comment by luctus** [comment]
it looks like debugger gem's development is over. Did you try [byebug](https://github.com/deivid-rodriguez/byebug)?
